name: reelspark
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.9.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.7.0
  shared_preferences: ^2.3.2
  flutter_bloc: ^9.1.1
  kiwi: ^5.0.1
  sprintf: ^7.0.0
  flutter_svg: ^2.0.10+1
  logger: ^2.4.0
  connectivity_plus: ^7.0.0
  cached_network_image: ^3.4.1
  built_value: ^8.9.5
  built_collection: ^5.1.1
  get_localization: ^3.0.0
  flutter_styled_toast: ^2.2.1
  image_picker: ^1.1.2
  file_picker: ^9.0.2
  google_fonts: ^6.2.1
  collection:
  loading_more_list: ^7.1.0
  path_provider: ^2.0.13
  share_plus: ^12.0.1
  upgrader:
  pinput: ^6.0.1
  country_picker: ^2.0.26
  
  #sign_in_with_apple: ^6.1.3

  #uni_links: ^0.5.1
  intl: 0.20.2
  material: ^1.0.0+2
  lottie: ^3.3.0
  wakelock_plus: ^1.2.10
  just_audio: ^0.10.5
  url_launcher: ^6.3.1
  firebase_messaging: ^16.1.0
  flutter_local_notifications: ^19.5.0
  webview_flutter: ^4.10.0
  package_info_plus: ^9.0.0
  encrypt: ^5.0.3
  firebase_crashlytics: ^5.0.6
  build_runner: ^2.4.13
  built_value_generator: ^8.9.2
  vibration: ^3.1.5
  audioplayers: ^6.0.0
  uuid: ^4.3.3
  on_audio_query: ^2.9.0
  media_store_plus: ^0.1.3

  # Local music library (Android/iOS) listing
  permission_handler: ^12.0.0

  # used for test


  video_player: ^2.9.1

  ffmpeg_kit_flutter_new: ^4.1.0
  image: ^4.5.4

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.3
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  kiwi_generator: ^4.1.0
  bloc_test: ^10.0.0
  mockito: ^5.3.2
  fake_async: ^1.3.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audio/
    - assets/stickers/
    #testing templates
    - assets/templates/
    - assets/templates/previews/
    - assets/templates/music/
    - assets/templates/stickers/
  #    - assets/frames/personal/
  #    - assets/frames/business/
  #    - assets/frames/quotes/
  #
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
    - family: Lobster
      fonts:
        - asset: assets/fonts/Lobster-Regular.ttf
          weight: 400
    - family: Playfair
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Regular.ttf
          weight: 400
    - family: Bebas
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf
          weight: 400


# App launcher icon
flutter_icons:
  android: true
  ios: true
  image_path: assets/images/app_logo.png


# Native Branding Screen
flutter_native_splash:
  android: true
  ios: true

  color: "#FFFFFF"

  android_12:
    color: "#FFFFFF"
